enabled: true
production-mode: true
grid-size: grid-xl
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/logoWEB.png:
    name: logoWEB.png
    type: image/png
    size: 11188
    path: user/themes/quark/images/logo/logoWEB.png
custom_logo_mobile:
  user/themes/quark/images/logo/logoWEB.png:
    name: logoWEB.png
    type: image/png
    size: 11188
    path: user/themes/quark/images/logo/logoWEB.png
